Repository thoth-station/integration-tests, pull requests merged in 2020-09, with the labels that each got.

#41 Automatic update of dependency thamos from 0.11.1 to 0.12.0
  Pipfile.lock
Labels: approved, bot, size/M

#43 Automatic update of dependency thamos from 0.12.0 to 0.12.2
  Pipfile.lock
Labels: approved, bot, size/L

#44 Automatic update of dependency thoth-storages from 0.25.5 to 0.25.6
  Pipfile.lock
Labels: approved, bot, size/L

#34 Validate TLS endpoints
  README.rst
  features/aggregate_build_logs.feature
  test.sh
Labels: approved, size/XS

#45 Automatic update of dependency thamos from 0.12.2 to 1.0.0
  Pipfile.lock
Labels: approved, bot, size/M

#46 Automatic update of dependency thoth-storages from 0.25.6 to 0.25.10
  Pipfile.lock
Labels: approved, bot, size/M
