Repository thoth-station/integration-tests, pull requests merged in 2020-08, with the labels that each got.

#37 Automatic update of dependency thamos from 0.10.6 to 0.11.1
  Pipfile.lock
Labels: approved, bot, size/L

#39 Remove limit_latest_versions
  features/steps/basic.py
Labels: size/XS

#38 Automatic update of dependency thoth-storages from 0.25.0 to 0.25.5
  Pipfile.lock
Labels: approved, bot, size/XS
