Repository thoth-station/integration-tests, pull requests merged in 2020-10, with the labels that each got.

#48 Automatic update of dependency thamos from 1.0.0 to 1.0.1
  Pipfile.lock
Labels: approved, bot, size/L

#49 Automatic update of dependency thoth-storages from 0.25.10 to 0.25.14
  Pipfile.lock
Labels: approved, bot, size/L

#51 Automatic update of dependency thoth-storages from 0.25.14 to 0.25.15
  Pipfile.lock
Labels: approved, bot, size/S

#53 Check on workflow status state
  features/steps/basic.py
Labels: size/XS

#54 Package Indices should be atleast 2 in deployment
  features/package_metadata.feature
  features/steps/index.py
Labels: approved, size/XS
