Repository thoth-station/integration-tests, pull requests merged in 2020-11, with the labels that each got.

#56 check solver names match a pattern
  features/solvers.feature
  features/steps/basic.py
  features/steps/solvers.py
Labels: approved, size/S

#58 Automatic update of dependency thamos from 1.0.1 to 1.2.0
  Pipfile.lock
Labels: approved, bot, size/L

#59 Automatic update of dependency thoth-storages from 0.25.15 to 0.26.0
  Pipfile.lock
Labels: approved, bot, size/L

#61 exclude db connection checking using tags
  features/db_status.feature
  test.sh
Labels: approved, size/XS

#62 Automatic update of dependency thamos from 1.2.0 to 1.3.1
  Pipfile.lock
Labels: approved, bot, size/S

#63 Automatic update of dependency thoth-storages from 0.26.0 to 0.26.1
  Pipfile.lock
Labels: approved, bot, size/S

#57 schedule solver jobs
  README.rst
  features/solvers.feature
  features/steps/basic.py
  features/steps/solvers.py
Labels: approved, size/M

#64 Automatic update of dependency requests from 2.24.0 to 2.25.0
  Pipfile.lock
Labels: approved, bot, size/S
