Repository thoth-station/integration-tests, pull requests merged in 2020-07, with the labels that each got.

#22 Automatic update of dependency thoth-storages from 0.23.2 to 0.24.4
  Pipfile.lock
Labels: approved, bot, size/L

#21 Automatic update of dependency thamos from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: approved, bot, size/L

#11 add amun features
  .env.template
  Pipfile
  Pipfile.lock
  features/aggregate_build_logs.feature
  features/steps/amun_api.py
Labels: approved, size/L

#26 Add THOTH_AMUN_API_HOST
  features/aggregate_build_logs.feature
  test.sh
Labels: size/XS

#29 Automatic update of dependency amun from 0.4.3 to 0.5.0
  Pipfile.lock
Labels: approved, bot, size/M

#28 Automatic update of dependency thoth-storages from 0.24.4 to 0.25.0
  Pipfile.lock
Labels: approved, bot, size/M
