Repository thoth-station/integration-tests, pull requests merged in 2021-02, with the labels that each got.

#76 Add standard Thoth GitHub templates
  .github/ISSUE_TEMPLATE/kebechet_info.md
  .github/ISSUE_TEMPLATE/kebechet_update.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/M

#75 Add version file
  version.py
Labels: approved, size/S

#83 Implement scenario for obtaining deployment information
  features/deployment_info.feature
  features/steps/deployment_info.py
Labels: approved, size/M

#82 Allow passing parameters to behave runs
  test.sh
Labels: approved, size/XS

#85 Extend Python Package index scenarios
  features/python_package_index.feature
  features/steps/index.py
  features/steps/python_package_index.py
Labels: approved, size/L

#86 Enable TLS verification when running integration tests
  features/steps/amun_api.py
  features/steps/basic.py
  features/steps/environment.py
  features/steps/python_package_metadata.py
Labels: approved, lgtm, size/S

#87 Add scenarios related to testing Python platform listing
  features/python_platform.feature
  features/steps/basic.py
  features/steps/python_platform.py
Labels: approved, lgtm, size/M

#81 Remove environments scenarios
  features/environments.feature
  features/steps/environment.py
Labels: size/M

#89 Remove database status integration tests
  features/db_status.feature
  features/steps/db_status.py
Labels: approved, lgtm, size/M

#88 Add scenarios related to Python s2i endpoints
  features/python_s2i.feature
  features/steps/python_s2i.py
Labels: approved, lgtm, size/M

#90 Fix pre-commit issues
  features/steps/python_s2i.py
Labels: approved, size/XS

#91 Add testcase for RHODS stack
  features/data/rhods/Pipfile
  features/steps/basic.py
  features/thamos_advise.feature
Labels: approved, size/M

#92 Changes required in adviser response handling
  features/steps/basic.py
Labels: approved, size/M

#98 Refactor integration tests for advise
  features/steps/advise.py
  features/steps/common.py
Labels: size/L

#99 Make sure adviser logs are accessible and available to users
  features/steps/advise.py
  features/thamos_advise.feature
Labels: size/S

#96 Package indexes are now tested by Package Index feature
  features/package_metadata.feature
Labels: size/XS

#97 Introduce tests related to container image analysis
  features/image_analysis.feature
  features/steps/image_analysis.py
Labels: size/L

#100 Add tests for build analyses
  features/build_analysis.feature
  features/data/buildlogs/generic.json
  features/data/project/flask_py36/Pipfile
  features/data/project/rhods/Pipfile
  features/steps/advise.py
  features/steps/build_analysis.py
  features/steps/common.py
Labels: size/L

#102 Add tests for obtaining versions and dependencies of packages
  features/package_metadata.feature
  features/steps/python_package_metadata.py
Labels: size/L

#104 Use scenario outline for similar advise tests
  features/thamos_advise.feature
Labels: size/S

#103 Introduce scenario for provenance check
  features/data/project/provenance_flask/Pipfile
  features/data/project/provenance_flask/Pipfile.lock
  features/steps/provenance_check.py
  features/thamos_provenance_check.feature
Labels: size/L

#105 Provide Python version parameter to advise scenario
  features/data/project/rhods/Pipfile
  features/steps/advise.py
  features/thamos_advise.feature
Labels: size/S

#106 Bump black version
  .pre-commit-config.yaml
  features/steps/advise.py
  features/steps/provenance_check.py
  features/steps/python_package_metadata.py
Labels: size/S

#107 Adjust integration tests based on adjusted responses
  features/steps/python_package_index.py
  features/steps/python_package_metadata.py
Labels: lgtm, size/XS

#109 Turn integration-tests into Thoth Python s2i application
  .aicoe-ci.yaml
  .env.template
  .gitignore
  Dockerfile
  Pipfile
  Pipfile.lock
  README.rst
  app.py
  behave.ini
  e2e-test.sh
  test.sh
Labels: approved, size/L

#110 Send integration-test results to aicoe-thoth-devops
  app.py
Labels: approved, size/XS

#113 Implement scenarios for testing an advise on a Git repo
  Pipfile
  Pipfile.lock
  features/steps/advise.py
  features/thamos_advise.feature
Labels: approved, size/L

#119 Configure advise scenario to send user stack and code analysis
  features/steps/advise.py
  features/thamos_advise.feature
Labels: approved, size/M

#118 Send the report as attachment
  app.py
Labels: approved, size/S

#133 Use proper status response
  features/steps/advise.py
  features/steps/image_analysis.py
  features/steps/provenance_check.py
Labels: approved, size/S

#134 Include integration-tests version in e-mail subject
  app.py
  version.py
Labels: approved, size/S

#135 Adjust listing of submitted advises from integration-tests
  features/thamos_advise.feature
Labels: size/XS

#138 Monitor OCP CI analysis repo
  features/thamos_advise.feature
Labels: size/XS

#137 Provide support for tags passed
  app.py
  features/aggregate_build_logs.feature
  features/build_analysis.feature
  features/image_analysis.feature
  features/thamos_advise.feature
  features/thamos_provenance_check.feature
Labels: size/S

#136 add script to install dependencies and run integration test
  README.rst
  app.py
Labels: size/M

#143 Add Amun inspection namespace to deployment info response
  features/steps/deployment_info.py
Labels: approved, size/XS

#142 Propagate behave exit code
  app.py
Labels: approved, size/XS

#148 Be more verbose if metadata feature fails
  features/steps/python_package_metadata.py
Labels: size/XS

#150 Reset config once advise_here is done
  features/steps/advise.py
Labels: size/S
