Repository thoth-station/integration-tests, pull requests merged in 2021-05, with the labels that each got.

#186 fix s2i image availabilty check
  features/steps/python_s2i.py
Labels: approved, size/XS

#185 change the dir to runtime environment
  features/steps/advise.py
Labels: approved, size/M

#189 updated anaylsis response check scenario and fix platform scenario name
  features/python_platform.feature
  features/steps/advise.py
Labels: approved, size/S

#190 Return error message if the package resolution is not available
  features/steps/advise.py
Labels: approved, size/XS

#191 Add Harshad to the maintainers listing
  .thoth.yaml
  OWNERS
Labels: approved, size/XS

#195 update the prow resource limits
  .prow.yaml
  .thoth.yaml
Labels: approved, size/S
