Repository thoth-station/integration-tests, pull requests merged in 2022-02, with the labels that each got.

#242 Fix package_metadata feature
  features/package_metadata.feature
  features/steps/python_package_metadata.py
Labels: approved, size/M

#244 Fix type of assert_that argument
  features/steps/python_package_metadata.py
Labels: approved, size/XS

#246 Update container_images feature tests according to new content format
  features/steps/container_images.py
Labels: approved, size/S

#257 Add username to approvers and reviewers
  OWNERS
Labels: approved, size/XS

#258 Use dash instead of colon in the runtime environment entry
  features/thamos_advise.feature
Labels: approved, size/XS

#260 Increase dependency monkey timeout
  features/steps/dependency_monkey.py
Labels: approved, size/XS

#256 Advise can take up to 20 minutes, add some time
  features/steps/advise.py
Labels: approved, size/XS
