Repository thoth-station/integration-tests, pull requests merged in 2022-01, with the labels that each got.

#229 Update integration tests related to package metadata
  features/package_metadata.feature
  features/steps/python_package_metadata.py
Labels: approved, size/M

#230 Update scenarios related to container images
  features/container_images.feature
  features/python_s2i.feature
  features/steps/container_images.py
  features/steps/python_s2i.py
Labels: size/L, approved

#231 Update advise and provenance features
  features/data/project/flask_py36/Pipfile
  features/data/project/provenance_flask/Pipfile
  features/data/project/provenance_flask/Pipfile.lock
  features/steps/advise.py
  features/thamos_advise.feature
Labels: size/L, approved

#232 Remove TODO by using the expected Thamos' config method
  features/steps/advise.py
Labels: approved, size/XS

#237 Add thoth-station/cli-examples to integration-tests
  features/thamos_advise.feature
Labels: approved, size/XS

#238 fix the container image testing
  features/steps/container_images.py
Labels: approved, size/XS
