Repository thoth-station/integration-tests, pull requests merged in 2023-01, with the labels that each got.

#364 :pushpin: Pinned behave-html-formatter to v0.9.7 for rendering in gmail
  Pipfile
  Pipfile.lock
Labels: approved, size/XL, lgtm

#365 update pipfile lock
  .pre-commit-config.yaml
  OWNERS
  Pipfile.lock
Labels: approved, size/M, lgtm

#369 :ship: Release of version 0.11.5
  .thoth.yaml
  CHANGELOG.md
  app.py
Labels: size/S
